spring:
  datasource:
    url: jdbc:h2:mem:testdb
  shell:
    interactive:
      enabled: true
  h2:
    console:
      enabled: true
  data:
    mongodb:
      database: library
  sql:
    init:
      mode: always
mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw_08.mongock.changelog
