spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  data:
    mongodb:
      database: library
  sql:
    init:
      mode: always
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw_11.changelog